### ISSUE TITLE
node.js — reapply global modules

### ISSUE THREAD

**Issue by Yeti-or** [markelog/eclectica#62]
how about not ?

**Comment by markelog** [comment]
It to slow, error prone, or something like that?

**Comment by Yeti-or** [comment]
1 slow and 2 I have errors
3 could it be optional ?

**Comment by Yeti-or** [comment]
for example global modules could be installed from private registry
when reapplying you don't catch error and fail on installing specified node.js version
or another one - if I have no internet connection ( in flight for example) I could not switch node.js version =(

**Comment by markelog** [comment]
A little backstory, there is two main version changer for nodejs right now – `n` and `nvm`.
Whereas `n` has common place global modules between various node versions. Which causes issues if you switching between very old and new node version i.e. – "0.10" to `6.x` or something. 

Modules that use gyp compilation will fail in such case.

By default `nvm`, on the other hand, will reinstall modules only with passed `--reinstall-packages-from` argument. And of course has separate global `node_modules` for each installed version. Nowadays they also support the `default-packages` feature too.

`eclectica` in this case, tries to reinstall global modules with recently added `--offline` flag (not yet even properly documented I believe) from the disk and make any network requests (at least in most cases).

Since flag was added only recently it might will not work on more older versions of node.

I was wondering if those two approached could be united in some way.

Given that current approach is not really stable and reinstall of global modules eventually (depends on how many modules we moving around) is slow, plus the fact that I don't do it for other supported languages.

I guess hiding this behaviour under the flag should indeed be the best course of actions
